apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    app: db
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
